### ISSUE TITLE
Reproducing experiments

### ISSUE THREAD

**Issue by icysapphire** [google-research/l2p#12]
Hello,
thanks for sharing the code, since it seems to be a pretty simple yet general idea which deserves further investigation. We are trying to reproduce the experiments in order to design possible extensions.
However, in the paper we can see results on cifar100, 5-datasets, CORe50 but in the code it seems that among them, only cifar is supported (and we can't find any code for running the baseline experiments consistently).

Is the released version of the code a non-final version? If so, we are kindly asking you to release the full code related to the published paper, in particular the libml/input_pipeline.py and all the relevant configs file.

Thank you for your time and consideration

**Comment by KingSpencer** [comment]
Hi,

Thanks for your interest! The datasets are in the newer version now! I am still doing some sanity checks (a little bit slow due to my limited availability) and hope you can leverage them well.

Best,
Zifeng

**Comment by icysapphire** [comment]
Thanks for the time you spent in the process. I think that having the code for running the competitor methods (e.g. EWC, ER and DER++) would be crucial in order to experiment in different settings / learning problems. Is it possible?

**Comment by Sande33p** [comment]
I`m curious if the code to compare with competitor methods is added along with the training scenario as I am not able to find it in the current release.
