### ISSUE TITLE
Reproduce issue

### ISSUE THREAD

**Issue by Lee-JH-KR** [google-research/l2p#13]
Dear author.

Thank you for your great work.

I'm having a little problem with reproducing L2P.

First, please modify the environment setup of README.md.

The link for adjust the jax version in README does not support CUDA version.
I think the link

> https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

seems to have changed to the link above.

The other thing is that even if batch_size is set to 1, I can't run the code completely in my 4 A5000 GPUs because of out of memory issue.
**Can you also provide small models such as ViT-Tiny or ViT-Small?**

I look forward to hearing from you.

Thank you.

**Comment by KingSpencer** [comment]
Hi,

Thanks for your catch! I have updated the environment setup and the codebase (I am also doing some sanity check now), also please try newer version of jax and flax. The codebase actually supports various sizes of ViT's and you can find corresponding pretrained models here: https://github.com/google-research/vision_transformer.

Best,
Zifeng
