### ISSUE TITLE
ReadMe issues

### ISSUE THREAD

**Issue by adocaj** [google-research/l2p#14]
I am trying to reproduce the results of the tables included in your nice paper. And I don't think that the code you have provided allows me to reproduce the results of Table 3.
Table 3 uses CORe50, and I was curious to know when the code that produces the results of Table 3 will be available.

Sorry to take your time with this, and hope you are doing well.

**Comment by KingSpencer** [comment]
Hi, 

Thanks for your interest, I have added that part into the codebase. However, you need to prepare the dataset yourself following the tutorial in README if you want to use CORe50. I am also thinking about better ways to make the prepared data accessible.

Best,
Zifeng

**Comment by adocaj** [comment]
Thank you so much for all your help, and for taking the time to address my issue.
