### ISSUE TITLE
ImportError: cannot import name 'resnet_v1' from 'models' (unknown location)

### ISSUE THREAD

**Issue by hubblezhang** [google-research/l2p#16]
In the File "/media/iiau/LiGong4T2/zwb/code/l2p/train_continual.py", line 42, I can see:

`from models import resnet_v1`

 but in "./models" folder, i can't find resnet_v1, so I get error like this:

> ImportError: cannot import name 'resnet_v1' from 'models' (unknown location)

How to solve this problem? Thanks!

**Comment by prateeky2806** [comment]
Hi, I am facing a similar issue. I could get the model to work for a ViT based model but I want to check the performance when using ResNet based model. Can you please provide the missing file and what changes are required to be in the config file for this.

Thanks!

**Comment by KingSpencer** [comment]
Hi,

Thanks for pointing this out! The model was deleted by mistake in the previous update. I have added it back.

Best,
Zifeng

**Comment by prateeky2806** [comment]
Hi @KingSpencer, does using model_name as resnet in config file lead to a setting where resnet is used as the base model classification or does it use resnet model as a query function? 
Can you please also mention the changes needed to be done in the cifar100 config file and the command line to make it work with resnet as a base model as opposed to vit. 

Thanks in Advance!
