### ISSUE TITLE
about providing the class orders.

### ISSUE THREAD

**Issue by zhaoedf** [google-research/l2p#26]
i was wondering if you could provide the seed and the corresponding class orders used in your imagenet-r experiment?

**Comment by KingSpencer** [comment]
Hi,

As mentioned in https://github.com/google-research/l2p/issues/27, I map class labels to 0-199 and then split in the natural order, i.e., 0-19, 20-39, etc. 

A better way is to try different splits (by playing with the seeds) and report the average performance.

Best,
Zifeng
