### ISSUE TITLE
Question regarding the average and last accuracy.

### ISSUE THREAD

**Issue by vgthengane** [google-research/l2p#29]
Dear authors,

Thank you for open-sourcing your work. I am slightly confused about the metrics you guys used for the evaluation. Here is my understanding from your readme.
1. `accuracy_n`: accuracy evaluation on only the n-th task after training for the n-th task.
2. `forgetting`: Average forgetting up until the current task.
3. `avg_acc`: Average evaluation accuracy after training for the n-th task. 
```
for (3), after training for the n-th task, we got,
acc_per_task = [a1, a2,...an];
avg_acc = average(acc_per_task);
```

Is it right?

**Comment by KingSpencer** [comment]
Yeah, I think your understanding is correct:)
