### ISSUE TITLE
Questions about the pre-trained ViT

### ISSUE THREAD

**Issue by zhoudw-zdw** [google-research/l2p#31]
Dear authors,

Thanks for your great job in building CIL learners with pre-trained models. I have a simple question regarding the pre-trained ViT. I noticed there are several versions of pre-trained ViT on the market. Seeing the fact that the current repo suggests downloading the pre-trained model from https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz, does it mean the model is pre-trained with IN21K? 

Thx in advance.

**Comment by KingSpencer** [comment]
Yes, that should be the default configuration.
